{{- /* vim: set ft=helm: */ -}}
{{- if and .Values.ingressEnabled .Values.authserver.adminHostname .Values.nginxIngressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeta-guard-admin-minion
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.nginxIngressEnabled }}
    nginx.org/mergeable-ingress-type: "minion"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if .Values.openshiftIngress.enabled }}
  tls:
    - hosts:
        - {{ .Values.authserver.adminHostname | quote }}
      secretName: {{ .Values.authserver.adminTlsSecretName | default "zeta-guard-admin-tls" | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.authserver.adminHostname | quote }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authserver
                port:
                  {{- if or .Values.authserver.hsm.tls.enabled .Values.authserver.tls.enabled }}
                  name: https
                  {{- else }}
                  name: http
                  {{- end }}
{{- end }}
