{{- if and .Values.global.istio.enabled .Values.nginxIngressEnabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: nginx-ingress-permissive
  labels:
    app.kubernetes.io/part-of: zeta-guard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress
  mtls:
    mode: PERMISSIVE
{{- end }}
