{{- if .Values.pepproxy.asl_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: roots-json
  labels:
    app.kubernetes.io/name: roots-json
    app.kubernetes.io/component: zeta-guard
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
type: Opaque
data:
  roots.json: {{ $.Files.Get "files/ru-roots.json" | b64enc | quote }}
{{- end }}
