apiVersion: apps/v1
kind: Deployment
metadata:
  name: testfachdienst
  labels:
    component: testfachdienst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testfachdienst
  template:
    metadata:
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
      labels:
        app: testfachdienst
        component: testfachdienst
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: testfachdienst
          image: "{{ default (printf "%s%s" .Values.global.registry_host .Values.registry_name) .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: MANAGEMENT_SERVER_PORT
              value: {{ .Values.managementPort | quote }}
          {{- with .Values.env }}
          {{- range . }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: app
            - containerPort: {{ .Values.managementPort }}
              name: management
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
