{{- if and .Values.notificationService.enabled .Values.notificationService.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.notificationService.serviceAccountName | quote }}
  labels:
    {{- include "zeta-guard.baseLabels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
automountServiceAccountToken: false
{{- end }}
