{{- if .Values.notificationService.enabled }}
{{- range $variant := list "rs" "fdv" }}
{{- $ctx := dict "root" $ "variant" $variant }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notificationService.fullname" $ctx }}
  labels:
    {{- include "notificationService.labels" $ctx | nindent 4 }}
spec:
  selector:
    {{- include "notificationService.selectorLabels" $ctx | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
{{- end }}
{{- end }}
