apiVersion: v2
name: zeta-testenv
description: ZETA Guard test installation
type: application
version: 1.3.3
dependencies:
  - name: testfachdienst
    version: 0.0.1
    tags:
      - testfachdienst
  - name: hsmsim
    version: 0.0.1
    condition: hsmsim.enabled
    tags:
      - hsmsim
  - name: popp-mocks
    version: 0.0.1
    condition: popp-mocks.enabled
    tags:
      - popp-mocks
  - name: test-monitoring-service
    version: 0.1.0
    alias: testMonitoringService
    condition: testMonitoringServiceEnabled
  - name: zeta-guard
    version: 1.3.3
    tags:
      - zeta-guard
  - name: testdriver
    version: 0.0.1
    tags:
      - testdriver
  - name: nativedriver
    version: 0.0.1
    tags:
      - nativedriver
  - name: tiger-proxy
    version: 0.0.1
    tags:
      - tiger-proxy
  - name: tiger-testsuite
    version: 0.0.1
    tags:
      - tiger-testsuite
  - name: zeta-tls-test-tool-service
    version: 0.1.0
    condition: zetaTlsTestToolServiceEnabled
  - name: zeta-cert-validation-mock
    version: 0.1.0
    condition: zetaCertValidationMockEnabled
  - name: load-dispenser
    version: 0.0.1
    condition: load-dispenser.enabled
    tags:
      - load-dispenser
  - name: lgtm
    version: 0.0.1
    condition: lgtm.enabled
    tags:
      - lgtm
  - name: infinispan-external
    version: 0.0.1
    tags:
      - infinispan-external
  - name: push-gateway
    version: 0.0.1
    repository: file://charts/push-gateway
    condition: push-gateway.enabled
  - name: sekidp
    version: 0.0.1
    repository: file://charts/sekidp
    condition: sekidp.enabled
  - name: mailcatcher
    version: 0.0.1
    repository: file://charts/mailcatcher
    condition: mailcatcher.enabled
