# Generated by generate-main-and-backend.sh (use_kubernetes=true) — do not edit.
#
# Generation is driven by the TF_VAR_use_kubernetes environment variable, while
# var.use_kubernetes comes from the tfvars file. If the two disagree, the
# generated files do not match the configuration (wrong backend, missing
# kubernetes_* resources), which fails in confusing ways. Catch it explicitly.
check "generated_mode_matches_variable" {
  assert {
    condition     = var.use_kubernetes
    error_message = "This configuration was generated for use_kubernetes = true, but var.use_kubernetes is false. Re-run `make generate-main-and-backend` with TF_VAR_use_kubernetes=false."
  }
}
