# Generated by generate-main-and-backend.sh (use_kubernetes=false) — do not edit.
#
# See the k8s variant for why this assertion exists.
check "generated_mode_matches_variable" {
  assert {
    condition     = !var.use_kubernetes
    error_message = "This configuration was generated for use_kubernetes = false, but var.use_kubernetes is true. Re-run `make generate-main-and-backend` with TF_VAR_use_kubernetes=true."
  }
}
