# Generated by generate-main-and-backend.sh (use_kubernetes=true) — do not edit.
# Source: templates/sekidp-secret.k8s.tpl
#
# The SekIdP entity-statement public key is published to the fedmaster as a
# Kubernetes Secret. This needs cluster access, so the file is emitted only in
# Kubernetes mode — keeping the kubernetes_* block (and with it the Kubernetes
# provider requirement) out of the configuration in local mode. The rollout
# resource lives here too because it depends_on the Secret.
#
# enable_sekidp = true is rejected in local mode by the validation on the
# variable in variables.tf.

resource "kubernetes_secret_v1" "sekidp_rp01_pubkey" {
  count = var.enable_sekidp ? 1 : 0

  metadata {
    name      = "sekidp-rp01-pubkey"
    namespace = var.keycloak_namespace
  }

  data = {
    "pubkey.pem" = data.external.entity_statement_pubkey[0].result.pubkey_pem
    "keyid"      = data.external.entity_statement_pubkey[0].result.kid
  }
}

# Restart gsi-fedmaster only when the kid changed — the standard way to pick up
# a changed Secret (kubelet doesn't do it automatically).
resource "terraform_data" "sekidp_fedmaster_rollout" {
  count = var.enable_sekidp ? 1 : 0

  triggers_replace = {
    keyid = data.external.entity_statement_pubkey[0].result.kid
  }

  provisioner "local-exec" {
    command = "kubectl -n ${var.keycloak_namespace} rollout restart deployment/sekidp-fedmaster"
  }

  depends_on = [kubernetes_secret_v1.sekidp_rp01_pubkey]
}
