{{- if and .Values.global.infinispanExternal.enabled (not .Values.global.infinispanExternal.admin.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: infinispan-admin
type: Opaque
stringData:
  username: "{{ required "infinispan admin username is missing" .Values.global.infinispanExternal.admin.username }}"
  password: "{{ required "infinispan admin password is missing" .Values.global.infinispanExternal.admin.password }}"
{{- end}}