apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-gateway-artemis
  labels:
    {{- include "push-gateway-artemis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "push-gateway-artemis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "push-gateway-artemis.labels" . | nindent 8 }}
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: artemis
          image: "{{ include "push-gateway-artemis.image" . }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: core
              containerPort: 61616
          env:
            - name: ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: push-gateway-artemis
                  key: username
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: push-gateway-artemis
                  key: password
            - name: ANONYMOUS_LOGIN
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /var/lib/artemis-instance
          {{- with .Values.artemis.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.artemis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          emptyDir: { }
