apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-gateway-postgres
  labels:
    {{- include "push-gateway-postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "push-gateway-postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "push-gateway-postgres.labels" . | nindent 8 }}
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 999
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ include "push-gateway-postgres.image" . }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: push-gateway-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: push-gateway-postgres
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: push-gateway-postgres
                  key: database
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.postgres.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          emptyDir: { }
