apiVersion: v1
kind: Secret
metadata:
  name: push-gateway-postgres
  labels:
    {{- include "push-gateway-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.credentials.username | quote }}
  password: {{ .Values.postgres.credentials.password | quote }}
  database: {{ .Values.postgres.credentials.database | quote }}
