apiVersion: v1
kind: Service
metadata:
  name: push-gateway-artemis
  labels:
    {{- include "push-gateway-artemis.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "push-gateway-artemis.selectorLabels" . | nindent 4 }}
  ports:
    - name: core
      port: 61616
      targetPort: core
  type: ClusterIP
