apiVersion: v1
kind: Service
metadata:
  name: push-gateway
  labels:
    {{- include "push-gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "push-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
  type: ClusterIP
