{{- if .Values.gsiServer.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sekidp-gsi-server
  labels:
    {{- include "sekidp-gsi-server.labels" . | nindent 4 }}
spec:
  {{- if not (kindIs "invalid" .Values.gsiServer.podDisruptionBudget.minAvailable) }}
  minAvailable: {{ .Values.gsiServer.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.gsiServer.podDisruptionBudget.maxUnavailable) }}
  maxUnavailable: {{ .Values.gsiServer.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sekidp-gsi-server.selectorLabels" . | nindent 6 }}
{{- end }}
