apiVersion: v1
kind: Service
metadata:
  name: sekidp-gsi-server
  labels:
    {{- include "sekidp-gsi-server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sekidp-gsi-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.gsiServer.service.apiPort }}
      targetPort: api
    - name: management
      port: {{ .Values.gsiServer.service.managementPort }}
      targetPort: management
  type: ClusterIP
