{{- if .Values.gsiServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gsiServer.serviceAccount.name }}
  labels:
    {{- include "sekidp-gsi-server.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
