{{- if .Values.fedmaster.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fedmaster.serviceAccount.name }}
  labels:
    {{- include "sekidp-fedmaster.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
