apiVersion: v1
kind: ConfigMap
metadata:
  name: pep-well-known
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
data:
  # TODO: brauchen wir das?
  # {{ .Values.authserver.hostname }}
{{- range $path, $file := .Files.Glob "files/well-known/*" }}
  {{ base $path }}: |-
{{ tpl ($file | toString) $ | indent 4 }}
{{- end }}
