{{- /* vim: set ft=helm: */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pep-deployment
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pepproxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "pep-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pep-proxy.labels" . | nindent 8 }}
        {{- with .Values.pepproxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.pepproxy.podAnnotations | or .Values.devMode | or .Values.pepproxy.nginxConf.generateConfigMap }}
      annotations:
        {{- with .Values.pepproxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.pepproxy.nginxConf.generateConfigMap }}
        {{- $nginxConf := include "zeta-guard.pep-nginx-conf" . }}
        checksum/nginx-conf: {{ $nginxConf | sha256sum }}
        {{- end }}
        {{- if .Values.devMode }}
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.pepproxy.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pepproxy.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          image: "{{ include "pep-proxy.image" . | trim }}"
          imagePullPolicy: "{{ .Values.pepproxy.imagePullPolicy }}"
          ports:
            - name: http-main
              containerPort: 8081
            - name: status
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /status
              port: status
          readinessProbe:
            httpGet:
              path: /status
              port: status
          {{- if .Values.pepproxy.containerSecurityContext }}
          securityContext:
          {{- toYaml .Values.pepproxy.containerSecurityContext | nindent 12 }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /status
              port: status
          {{- with .Values.pepproxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- if .Values.pepproxy.asl_enabled }}
            - name: roots-json
              mountPath: /etc/nginx/roots.json
              subPath: roots.json
              readOnly: true
            - name: asl-signer-cert
              mountPath: /etc/nginx/signer_cert.pem
              subPath: signer_cert.pem
              readOnly: true
            - name: asl-signer-key
              mountPath: /etc/nginx/signer_key.pem
              subPath: signer_key.pem
              readOnly: true
            - name: asl-issuer-cert
              mountPath: /etc/nginx/issuer_cert.pem
              subPath: issuer_cert.pem
              readOnly: true
            {{- end }}
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
            {{- /* use subPath to only project intended files, not ..data etc. */ -}}
            {{- $files := .Files.Glob "files/well-known/*" }}
            {{- range $path, $_ := $files }}
            - name: well-known
              mountPath: /srv/.well-known/{{ base $path }}
              subPath: {{ base $path }}
            {{- end }}

      {{- if .Values.pepproxyMetricsEnabled }}
        - name: metrics
          image: "{{ .Values.pepproxyMetricsExporterImage }}"
          command:
            - nginx-prometheus-exporter
          args:
            - --nginx.scrape-uri=http://$(MY_POD_IP):8080/status
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: metrics
              containerPort: 9113
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
          {{- if .Values.pepproxy.containerSecurityContext }}
          securityContext:
          {{- toYaml .Values.pepproxy.containerSecurityContext | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: "{{ .Values.pepproxy.nginxConf.configMapName }}"
            defaultMode: 0444
            items:
              - key: nginx.conf
                path: nginx.conf
        {{- if .Values.pepproxy.asl_enabled }}
        - name: roots-json
          secret:
            secretName: roots-json
            items:
              - key: roots.json
                path: "roots.json"
        - name: asl-signer-cert
          secret:
            secretName: asl-identity
            items:
              - key: signer-cert
                path: "signer_cert.pem"
        - name: asl-signer-key
          secret:
            secretName: asl-identity
            items:
              - key: signer-key
                path: "signer_key.pem"
        - name: asl-issuer-cert
          secret:
            secretName: asl-identity
            items:
              - key: issuer-cert
                path: "issuer_cert.pem"
        {{- end }}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: well-known
          configMap:
            name: pep-well-known
            defaultMode: 0444
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: zeta-pep
      {{- with .Values.pepproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pepproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
{{- if .Values.pepproxy.nginxConf.generateConfigMap }}
{{- $nginxConf := include "zeta-guard.pep-nginx-conf" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.pepproxy.nginxConf.configMapName }}"
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- $nginxConf | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: pep-proxy-svc
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pep-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http-main
    {{- if .Values.pepproxyMetricsEnabled }}
    - name: metrics
      port: 9113
      targetPort: metrics
    {{- end }}
  type: ClusterIP
