{{- if and .Values.opa.rolloutRestart.enabled (not .Values.opa.rolloutRestart.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-rollout-restart
  labels:
    {{- include "opa.labels" . | nindent 4 }}
{{- end }}
