{{- if .Values.opa.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
    {{- include "opa.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "opa.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8181
      targetPort: http
  type: ClusterIP
{{- if .Values.opa.simulation.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: opa-simulation
  labels:
    {{- include "opaSimulation.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "opaSimulation.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8181
      targetPort: http
  type: ClusterIP
{{- end }}
{{- end }}
