{{- $wif := .Values.opa.workloadIdentityFederation -}}
{{- if and .Values.opa.enabled .Values.opa.bundle.enabled (and $wif $wif.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: opa-gcp-token
  labels:
    {{- include "opa.labels" . | nindent 4 }}
type: Opaque
{{- end }}
