apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zeta-tls-test-tool-service"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "zeta-tls-test-tool-service"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zeta-tls-test-tool-service"
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: runtime
          emptyDir: {}
      containers:
        - name: zeta-tls-test-tool-service
          image: "{{ default (printf "%s%s" .Values.global.registry_host .Values.registry_name) .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: service-mgmt
              containerPort: {{ .Values.service.ports.serviceMgmtTargetPort }}
            - name: tls-test-tool
              containerPort: {{ .Values.service.ports.tlsTestToolServerTargetPort }}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: service-mgmt
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: service-mgmt
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: runtime
              mountPath: /app/runtime
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
