apiVersion: apps/v1
kind: Deployment
metadata:
  name: popp-mock
  labels:
    component: popp-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popp-mock
  template:
    metadata:
      labels:
        app: popp-mock
        component: popp-mock
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.tokenGenerator.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.tokenGenerator.enabled }}
        - name: popp-token-generator
          image: "{{ default (printf "%s%s" .Values.global.registry_host .Values.registry_name) .Values.tokenGenerator.image.registry }}{{ .Values.tokenGenerator.image.repository }}:{{ .Values.tokenGenerator.image.tag }}"
          imagePullPolicy: "{{ .Values.tokenGenerator.imagePullPolicy }}"
          env:
            - name: spring_profiles_active
              value: default,docker
          ports:
            - containerPort: 80
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: popp-statics
          {{- $poppStatics := .Values.poppStatics | default dict }}
          {{- $image := $poppStatics.image | default dict }}
          image: "{{ $image.registry | default "" }}{{ $image.repository | default "nginxinc/nginx-unprivileged" }}:{{ $image.tag | default "alpine3.22-slim" }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: jwks-file
              mountPath: "/usr/share/nginx/html/jwks.json"
              subPath: "jwks.json"
              readOnly: true
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: nginx-tmp
          emptyDir: { }
        - name: nginx-cache
          emptyDir: { }
        - name: jwks-file
          configMap:
            name: popp-jwks-file
            items:
              - key: jwks
                path: "jwks.json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: popp-jwks-file
data:
  jwks: |
    {
      "keys": [
        {
          "kty": "EC",
          "kid": "alias",
          "crv": "P-256",
          "x": "cC8jes-IzhTkcHMdMjJ6yf9lxlEe2_1XG6OVtNpE-28",
          "y": "2sqO5vyva24EQn8AgS6mONneRhII8qhRLq_VI06DxOE",
          "alg": "ES256",
          "use": "sig"
        }
      ]
    }
