apiVersion: v1
kind: Service
metadata:
  name: authserver
  labels:
    {{- include "authserver.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "authserver.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http-port
    - name: mgmt-interface
      port: 9000
      targetPort: http-mgmt-port
    {{- if .Values.devMode }}
    - name: jdwp
      port: 5005
      targetPort: jdwp
    {{- end }}
  type: ClusterIP
