apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiger-proxy
  labels:
    {{- include "tiger-proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tiger-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
      labels:
        {{- include "tiger-proxy.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # initContainers:
      #   - name: iptables-init
      #     image: alpine:3.20
      #     # Needs NET_ADMIN (and often privileged) to modify iptables
      #     securityContext:
      #       privileged: true
      #       capabilities:
      #         add:
      #           - NET_ADMIN
      #     command:
      #       - /bin/sh
      #       - -c
      #       - |
      #         set -e

      #         # Install iptables
      #         apk add --no-cache iptables

      #         # Traffic coming from outside the pod (to this pod IP:4138)
      #         iptables -t nat -A PREROUTING -p tcp --dport 4138 -j REDIRECT --to-ports 8080

      #         # Traffic originating from inside the pod going to :80 (localhost)
      #         # iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-ports 8080

      #         # Done - exit and let main containers start
      #         echo "iptables rules configured"

      containers:
        - name: nginx-sidecar
          image: "docker.io/nginxinc/nginx-unprivileged:alpine3.22-slim"
          ports:
            - name: otlp-http-port
              containerPort: 4138
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tiger-application-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-tmp
              mountPath: /tmp

        - name: {{ .Chart.Name }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ default (printf "%s%s" .Values.global.registry_host .Values.registry_name) .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          # TODO - review necessity of this section or rework
          ports:
            - name: proxy-port
              containerPort: {{ .Values.proxyConfig.proxyPort }}
            - name: admin-port
              containerPort: {{ .Values.proxyConfig.adminPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.startup.livenessProbe.url }}
              port: {{ .Values.startup.livenessProbe.port }}
            failureThreshold: {{ default .Values.startup.failureThreshold .Values.startup.livenessProbe.failureThreshold }}
            periodSeconds: {{ default .Values.startup.startupPeriodSeconds .Values.startup.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ default 120 .Values.startup.livenessProbe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.startup.readinessProbe.url }}
              port: {{ .Values.startup.readinessProbe.port }}
            failureThreshold: {{ default .Values.startup.failureThreshold .Values.startup.readinessProbe.failureThreshold }}
            periodSeconds: {{ default .Values.startup.startupPeriodSeconds .Values.startup.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ default 120 .Values.startup.readinessProbe.initialDelaySeconds }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - name: tiger-application-config
              mountPath: /app/application.yaml
              subPath: "application.yaml"
              readOnly: true
            - name: maven-target
              mountPath: /app/target
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tiger-application-config
          configMap:
            name: tiger-proxy
            items:
            - key: application.yaml
              path: application.yaml
            - key: application.grpc.yaml
              path: application.grpc.yaml
            - key: nginx.conf
              path: nginx.conf
        - name: maven-target
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
        - name: tmp
          emptyDir: {}
