{{- if .Values.global.istio.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: tiger-proxy-permissive
  labels:
    app.kubernetes.io/part-of: zeta-guard
spec:
  selector:
    matchLabels:
      {{- include "tiger-proxy.selectorLabels" . | nindent 6 }}
  mtls:
    mode: PERMISSIVE
{{- end }}
