apiVersion: v1
kind: Secret
metadata:
  name: test-smcb-keystore
type: Opaque
data:
  keystore: "{{ .Values.smcb_keystore.keystore | trim }}"
  password: "{{ .Values.smcb_keystore.password | trim | b64enc }}"
